/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PrivateSpaceConnectionPost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateSpaceConnectionPost{}

// PrivateSpaceConnectionPost struct for PrivateSpaceConnectionPost
type PrivateSpaceConnectionPost struct {
	Name string `json:"name"`
	Vpns []Items `json:"vpns"`
}

// NewPrivateSpaceConnectionPost instantiates a new PrivateSpaceConnectionPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateSpaceConnectionPost(name string, vpns []Items) *PrivateSpaceConnectionPost {
	this := PrivateSpaceConnectionPost{}
	this.Name = name
	this.Vpns = vpns
	return &this
}

// NewPrivateSpaceConnectionPostWithDefaults instantiates a new PrivateSpaceConnectionPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateSpaceConnectionPostWithDefaults() *PrivateSpaceConnectionPost {
	this := PrivateSpaceConnectionPost{}
	return &this
}

// GetName returns the Name field value
func (o *PrivateSpaceConnectionPost) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceConnectionPost) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PrivateSpaceConnectionPost) SetName(v string) {
	o.Name = v
}

// GetVpns returns the Vpns field value
func (o *PrivateSpaceConnectionPost) GetVpns() []Items {
	if o == nil {
		var ret []Items
		return ret
	}

	return o.Vpns
}

// GetVpnsOk returns a tuple with the Vpns field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceConnectionPost) GetVpnsOk() ([]Items, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vpns, true
}

// SetVpns sets field value
func (o *PrivateSpaceConnectionPost) SetVpns(v []Items) {
	o.Vpns = v
}

func (o PrivateSpaceConnectionPost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateSpaceConnectionPost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["vpns"] = o.Vpns
	return toSerialize, nil
}

type NullablePrivateSpaceConnectionPost struct {
	value *PrivateSpaceConnectionPost
	isSet bool
}

func (v NullablePrivateSpaceConnectionPost) Get() *PrivateSpaceConnectionPost {
	return v.value
}

func (v *NullablePrivateSpaceConnectionPost) Set(val *PrivateSpaceConnectionPost) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateSpaceConnectionPost) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateSpaceConnectionPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateSpaceConnectionPost(val *PrivateSpaceConnectionPost) *NullablePrivateSpaceConnectionPost {
	return &NullablePrivateSpaceConnectionPost{value: val, isSet: true}
}

func (v NullablePrivateSpaceConnectionPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateSpaceConnectionPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


