/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InternalDns9 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalDns9{}

// InternalDns9 The internal DNS config of the VPC that the Private Space uses. 
type InternalDns9 struct {
	DnsServers []string `json:"dnsServers"`
	SpecialDomains []string `json:"specialDomains"`
}

// NewInternalDns9 instantiates a new InternalDns9 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalDns9(dnsServers []string, specialDomains []string) *InternalDns9 {
	this := InternalDns9{}
	this.DnsServers = dnsServers
	this.SpecialDomains = specialDomains
	return &this
}

// NewInternalDns9WithDefaults instantiates a new InternalDns9 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalDns9WithDefaults() *InternalDns9 {
	this := InternalDns9{}
	return &this
}

// GetDnsServers returns the DnsServers field value
func (o *InternalDns9) GetDnsServers() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.DnsServers
}

// GetDnsServersOk returns a tuple with the DnsServers field value
// and a boolean to check if the value has been set.
func (o *InternalDns9) GetDnsServersOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DnsServers, true
}

// SetDnsServers sets field value
func (o *InternalDns9) SetDnsServers(v []string) {
	o.DnsServers = v
}

// GetSpecialDomains returns the SpecialDomains field value
func (o *InternalDns9) GetSpecialDomains() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SpecialDomains
}

// GetSpecialDomainsOk returns a tuple with the SpecialDomains field value
// and a boolean to check if the value has been set.
func (o *InternalDns9) GetSpecialDomainsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpecialDomains, true
}

// SetSpecialDomains sets field value
func (o *InternalDns9) SetSpecialDomains(v []string) {
	o.SpecialDomains = v
}

func (o InternalDns9) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalDns9) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dnsServers"] = o.DnsServers
	toSerialize["specialDomains"] = o.SpecialDomains
	return toSerialize, nil
}

type NullableInternalDns9 struct {
	value *InternalDns9
	isSet bool
}

func (v NullableInternalDns9) Get() *InternalDns9 {
	return v.value
}

func (v *NullableInternalDns9) Set(val *InternalDns9) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalDns9) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalDns9) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalDns9(val *InternalDns9) *NullableInternalDns9 {
	return &NullableInternalDns9{value: val, isSet: true}
}

func (v NullableInternalDns9) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalDns9) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


