/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TlsConfigJks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TlsConfigJks{}

// TlsConfigJks struct for TlsConfigJks
type TlsConfigJks struct {
	KeyStore KeyStoreJks `json:"keyStore"`
	TrustStore map[string]interface{} `json:"trustStore,omitempty"`
}

// NewTlsConfigJks instantiates a new TlsConfigJks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTlsConfigJks(keyStore KeyStoreJks) *TlsConfigJks {
	this := TlsConfigJks{}
	this.KeyStore = keyStore
	return &this
}

// NewTlsConfigJksWithDefaults instantiates a new TlsConfigJks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTlsConfigJksWithDefaults() *TlsConfigJks {
	this := TlsConfigJks{}
	return &this
}

// GetKeyStore returns the KeyStore field value
func (o *TlsConfigJks) GetKeyStore() KeyStoreJks {
	if o == nil {
		var ret KeyStoreJks
		return ret
	}

	return o.KeyStore
}

// GetKeyStoreOk returns a tuple with the KeyStore field value
// and a boolean to check if the value has been set.
func (o *TlsConfigJks) GetKeyStoreOk() (*KeyStoreJks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyStore, true
}

// SetKeyStore sets field value
func (o *TlsConfigJks) SetKeyStore(v KeyStoreJks) {
	o.KeyStore = v
}

// GetTrustStore returns the TrustStore field value if set, zero value otherwise.
func (o *TlsConfigJks) GetTrustStore() map[string]interface{} {
	if o == nil || IsNil(o.TrustStore) {
		var ret map[string]interface{}
		return ret
	}
	return o.TrustStore
}

// GetTrustStoreOk returns a tuple with the TrustStore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TlsConfigJks) GetTrustStoreOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TrustStore) {
		return map[string]interface{}{}, false
	}
	return o.TrustStore, true
}

// HasTrustStore returns a boolean if a field has been set.
func (o *TlsConfigJks) HasTrustStore() bool {
	if o != nil && !IsNil(o.TrustStore) {
		return true
	}

	return false
}

// SetTrustStore gets a reference to the given map[string]interface{} and assigns it to the TrustStore field.
func (o *TlsConfigJks) SetTrustStore(v map[string]interface{}) {
	o.TrustStore = v
}

func (o TlsConfigJks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TlsConfigJks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keyStore"] = o.KeyStore
	if !IsNil(o.TrustStore) {
		toSerialize["trustStore"] = o.TrustStore
	}
	return toSerialize, nil
}

type NullableTlsConfigJks struct {
	value *TlsConfigJks
	isSet bool
}

func (v NullableTlsConfigJks) Get() *TlsConfigJks {
	return v.value
}

func (v *NullableTlsConfigJks) Set(val *TlsConfigJks) {
	v.value = val
	v.isSet = true
}

func (v NullableTlsConfigJks) IsSet() bool {
	return v.isSet
}

func (v *NullableTlsConfigJks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTlsConfigJks(val *TlsConfigJks) *NullableTlsConfigJks {
	return &NullableTlsConfigJks{value: val, isSet: true}
}

func (v NullableTlsConfigJks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTlsConfigJks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


