/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PrivateSpaceConnection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateSpaceConnection{}

// PrivateSpaceConnection struct for PrivateSpaceConnection
type PrivateSpaceConnection struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Vpns []Items `json:"vpns"`
}

// NewPrivateSpaceConnection instantiates a new PrivateSpaceConnection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateSpaceConnection(id string, name string, vpns []Items) *PrivateSpaceConnection {
	this := PrivateSpaceConnection{}
	this.Id = id
	this.Name = name
	this.Vpns = vpns
	return &this
}

// NewPrivateSpaceConnectionWithDefaults instantiates a new PrivateSpaceConnection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateSpaceConnectionWithDefaults() *PrivateSpaceConnection {
	this := PrivateSpaceConnection{}
	return &this
}

// GetId returns the Id field value
func (o *PrivateSpaceConnection) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceConnection) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PrivateSpaceConnection) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *PrivateSpaceConnection) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceConnection) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PrivateSpaceConnection) SetName(v string) {
	o.Name = v
}

// GetVpns returns the Vpns field value
func (o *PrivateSpaceConnection) GetVpns() []Items {
	if o == nil {
		var ret []Items
		return ret
	}

	return o.Vpns
}

// GetVpnsOk returns a tuple with the Vpns field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceConnection) GetVpnsOk() ([]Items, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vpns, true
}

// SetVpns sets field value
func (o *PrivateSpaceConnection) SetVpns(v []Items) {
	o.Vpns = v
}

func (o PrivateSpaceConnection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateSpaceConnection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["vpns"] = o.Vpns
	return toSerialize, nil
}

type NullablePrivateSpaceConnection struct {
	value *PrivateSpaceConnection
	isSet bool
}

func (v NullablePrivateSpaceConnection) Get() *PrivateSpaceConnection {
	return v.value
}

func (v *NullablePrivateSpaceConnection) Set(val *PrivateSpaceConnection) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateSpaceConnection) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateSpaceConnection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateSpaceConnection(val *PrivateSpaceConnection) *NullablePrivateSpaceConnection {
	return &NullablePrivateSpaceConnection{value: val, isSet: true}
}

func (v NullablePrivateSpaceConnection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateSpaceConnection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


