/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Items type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Items{}

// Items struct for Items
type Items struct {
	// The name of the VPN. 
	Name string `json:"name"`
	// The id of the VPN. 
	VpnId *string `json:"vpnId,omitempty"`
	// The connectionId associated to the vpn, to which it belongs. 
	ConnectionId *string `json:"connectionId,omitempty"`
	// The connectionName associated to the vpn, to which it belongs. 
	ConnectionName *string `json:"connectionName,omitempty"`
	// The status of vpn(pending | available | deleting | deleted). 
	VpnConnectionStatus *string `json:"vpnConnectionStatus,omitempty"`
	// The ASN of the customer's outside network, used by VPNs utilizing BGP for routes. 
	RemoteAsn *float32 `json:"remoteAsn,omitempty"`
	// The ASN of the customer's cloudhub network, used by VPNs utilizing BGP for routes. 
	LocalAsn *float32 `json:"localAsn,omitempty"`
	// The IP address of the customer's VPN device on their outside network 
	RemoteIpAddress string `json:"remoteIpAddress"`
	// The CIDRs that the Cloudhub VPC will send traffic to via the VPN. 
	StaticRoutes []string `json:"staticRoutes"`
	// VPN tunnel actual state of customer's VPN connection.
	VpnTunnels []Items7 `json:"vpnTunnels"`
}

// NewItems instantiates a new Items object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItems(name string, remoteIpAddress string, staticRoutes []string, vpnTunnels []Items7) *Items {
	this := Items{}
	this.Name = name
	this.RemoteIpAddress = remoteIpAddress
	this.StaticRoutes = staticRoutes
	this.VpnTunnels = vpnTunnels
	return &this
}

// NewItemsWithDefaults instantiates a new Items object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemsWithDefaults() *Items {
	this := Items{}
	return &this
}

// GetName returns the Name field value
func (o *Items) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Items) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Items) SetName(v string) {
	o.Name = v
}

// GetVpnId returns the VpnId field value if set, zero value otherwise.
func (o *Items) GetVpnId() string {
	if o == nil || IsNil(o.VpnId) {
		var ret string
		return ret
	}
	return *o.VpnId
}

// GetVpnIdOk returns a tuple with the VpnId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Items) GetVpnIdOk() (*string, bool) {
	if o == nil || IsNil(o.VpnId) {
		return nil, false
	}
	return o.VpnId, true
}

// HasVpnId returns a boolean if a field has been set.
func (o *Items) HasVpnId() bool {
	if o != nil && !IsNil(o.VpnId) {
		return true
	}

	return false
}

// SetVpnId gets a reference to the given string and assigns it to the VpnId field.
func (o *Items) SetVpnId(v string) {
	o.VpnId = &v
}

// GetConnectionId returns the ConnectionId field value if set, zero value otherwise.
func (o *Items) GetConnectionId() string {
	if o == nil || IsNil(o.ConnectionId) {
		var ret string
		return ret
	}
	return *o.ConnectionId
}

// GetConnectionIdOk returns a tuple with the ConnectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Items) GetConnectionIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConnectionId) {
		return nil, false
	}
	return o.ConnectionId, true
}

// HasConnectionId returns a boolean if a field has been set.
func (o *Items) HasConnectionId() bool {
	if o != nil && !IsNil(o.ConnectionId) {
		return true
	}

	return false
}

// SetConnectionId gets a reference to the given string and assigns it to the ConnectionId field.
func (o *Items) SetConnectionId(v string) {
	o.ConnectionId = &v
}

// GetConnectionName returns the ConnectionName field value if set, zero value otherwise.
func (o *Items) GetConnectionName() string {
	if o == nil || IsNil(o.ConnectionName) {
		var ret string
		return ret
	}
	return *o.ConnectionName
}

// GetConnectionNameOk returns a tuple with the ConnectionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Items) GetConnectionNameOk() (*string, bool) {
	if o == nil || IsNil(o.ConnectionName) {
		return nil, false
	}
	return o.ConnectionName, true
}

// HasConnectionName returns a boolean if a field has been set.
func (o *Items) HasConnectionName() bool {
	if o != nil && !IsNil(o.ConnectionName) {
		return true
	}

	return false
}

// SetConnectionName gets a reference to the given string and assigns it to the ConnectionName field.
func (o *Items) SetConnectionName(v string) {
	o.ConnectionName = &v
}

// GetVpnConnectionStatus returns the VpnConnectionStatus field value if set, zero value otherwise.
func (o *Items) GetVpnConnectionStatus() string {
	if o == nil || IsNil(o.VpnConnectionStatus) {
		var ret string
		return ret
	}
	return *o.VpnConnectionStatus
}

// GetVpnConnectionStatusOk returns a tuple with the VpnConnectionStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Items) GetVpnConnectionStatusOk() (*string, bool) {
	if o == nil || IsNil(o.VpnConnectionStatus) {
		return nil, false
	}
	return o.VpnConnectionStatus, true
}

// HasVpnConnectionStatus returns a boolean if a field has been set.
func (o *Items) HasVpnConnectionStatus() bool {
	if o != nil && !IsNil(o.VpnConnectionStatus) {
		return true
	}

	return false
}

// SetVpnConnectionStatus gets a reference to the given string and assigns it to the VpnConnectionStatus field.
func (o *Items) SetVpnConnectionStatus(v string) {
	o.VpnConnectionStatus = &v
}

// GetRemoteAsn returns the RemoteAsn field value if set, zero value otherwise.
func (o *Items) GetRemoteAsn() float32 {
	if o == nil || IsNil(o.RemoteAsn) {
		var ret float32
		return ret
	}
	return *o.RemoteAsn
}

// GetRemoteAsnOk returns a tuple with the RemoteAsn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Items) GetRemoteAsnOk() (*float32, bool) {
	if o == nil || IsNil(o.RemoteAsn) {
		return nil, false
	}
	return o.RemoteAsn, true
}

// HasRemoteAsn returns a boolean if a field has been set.
func (o *Items) HasRemoteAsn() bool {
	if o != nil && !IsNil(o.RemoteAsn) {
		return true
	}

	return false
}

// SetRemoteAsn gets a reference to the given float32 and assigns it to the RemoteAsn field.
func (o *Items) SetRemoteAsn(v float32) {
	o.RemoteAsn = &v
}

// GetLocalAsn returns the LocalAsn field value if set, zero value otherwise.
func (o *Items) GetLocalAsn() float32 {
	if o == nil || IsNil(o.LocalAsn) {
		var ret float32
		return ret
	}
	return *o.LocalAsn
}

// GetLocalAsnOk returns a tuple with the LocalAsn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Items) GetLocalAsnOk() (*float32, bool) {
	if o == nil || IsNil(o.LocalAsn) {
		return nil, false
	}
	return o.LocalAsn, true
}

// HasLocalAsn returns a boolean if a field has been set.
func (o *Items) HasLocalAsn() bool {
	if o != nil && !IsNil(o.LocalAsn) {
		return true
	}

	return false
}

// SetLocalAsn gets a reference to the given float32 and assigns it to the LocalAsn field.
func (o *Items) SetLocalAsn(v float32) {
	o.LocalAsn = &v
}

// GetRemoteIpAddress returns the RemoteIpAddress field value
func (o *Items) GetRemoteIpAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RemoteIpAddress
}

// GetRemoteIpAddressOk returns a tuple with the RemoteIpAddress field value
// and a boolean to check if the value has been set.
func (o *Items) GetRemoteIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemoteIpAddress, true
}

// SetRemoteIpAddress sets field value
func (o *Items) SetRemoteIpAddress(v string) {
	o.RemoteIpAddress = v
}

// GetStaticRoutes returns the StaticRoutes field value
func (o *Items) GetStaticRoutes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.StaticRoutes
}

// GetStaticRoutesOk returns a tuple with the StaticRoutes field value
// and a boolean to check if the value has been set.
func (o *Items) GetStaticRoutesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StaticRoutes, true
}

// SetStaticRoutes sets field value
func (o *Items) SetStaticRoutes(v []string) {
	o.StaticRoutes = v
}

// GetVpnTunnels returns the VpnTunnels field value
func (o *Items) GetVpnTunnels() []Items7 {
	if o == nil {
		var ret []Items7
		return ret
	}

	return o.VpnTunnels
}

// GetVpnTunnelsOk returns a tuple with the VpnTunnels field value
// and a boolean to check if the value has been set.
func (o *Items) GetVpnTunnelsOk() ([]Items7, bool) {
	if o == nil {
		return nil, false
	}
	return o.VpnTunnels, true
}

// SetVpnTunnels sets field value
func (o *Items) SetVpnTunnels(v []Items7) {
	o.VpnTunnels = v
}

func (o Items) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Items) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.VpnId) {
		toSerialize["vpnId"] = o.VpnId
	}
	if !IsNil(o.ConnectionId) {
		toSerialize["connectionId"] = o.ConnectionId
	}
	if !IsNil(o.ConnectionName) {
		toSerialize["connectionName"] = o.ConnectionName
	}
	if !IsNil(o.VpnConnectionStatus) {
		toSerialize["vpnConnectionStatus"] = o.VpnConnectionStatus
	}
	if !IsNil(o.RemoteAsn) {
		toSerialize["remoteAsn"] = o.RemoteAsn
	}
	if !IsNil(o.LocalAsn) {
		toSerialize["localAsn"] = o.LocalAsn
	}
	toSerialize["remoteIpAddress"] = o.RemoteIpAddress
	toSerialize["staticRoutes"] = o.StaticRoutes
	toSerialize["vpnTunnels"] = o.VpnTunnels
	return toSerialize, nil
}

type NullableItems struct {
	value *Items
	isSet bool
}

func (v NullableItems) Get() *Items {
	return v.value
}

func (v *NullableItems) Set(val *Items) {
	v.value = val
	v.isSet = true
}

func (v NullableItems) IsSet() bool {
	return v.isSet
}

func (v *NullableItems) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItems(val *Items) *NullableItems {
	return &NullableItems{value: val, isSet: true}
}

func (v NullableItems) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItems) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


