/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Environments type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Environments{}

// Environments Environment association for the Private Space 
type Environments struct {
	// The type of environments. Possible values are all, sandbox, production
	Type string `json:"type"`
	// The Ids of business groups.
	BusinessGroups []string `json:"businessGroups"`
}

// NewEnvironments instantiates a new Environments object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironments(type_ string, businessGroups []string) *Environments {
	this := Environments{}
	this.Type = type_
	this.BusinessGroups = businessGroups
	return &this
}

// NewEnvironmentsWithDefaults instantiates a new Environments object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentsWithDefaults() *Environments {
	this := Environments{}
	return &this
}

// GetType returns the Type field value
func (o *Environments) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Environments) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Environments) SetType(v string) {
	o.Type = v
}

// GetBusinessGroups returns the BusinessGroups field value
func (o *Environments) GetBusinessGroups() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.BusinessGroups
}

// GetBusinessGroupsOk returns a tuple with the BusinessGroups field value
// and a boolean to check if the value has been set.
func (o *Environments) GetBusinessGroupsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BusinessGroups, true
}

// SetBusinessGroups sets field value
func (o *Environments) SetBusinessGroups(v []string) {
	o.BusinessGroups = v
}

func (o Environments) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Environments) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["businessGroups"] = o.BusinessGroups
	return toSerialize, nil
}

type NullableEnvironments struct {
	value *Environments
	isSet bool
}

func (v NullableEnvironments) Get() *Environments {
	return v.value
}

func (v *NullableEnvironments) Set(val *Environments) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironments) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironments) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironments(val *Environments) *NullableEnvironments {
	return &NullableEnvironments{value: val, isSet: true}
}

func (v NullableEnvironments) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironments) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


