/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PrivateSpaceTlsContextJksPost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateSpaceTlsContextJksPost{}

// PrivateSpaceTlsContextJksPost struct for PrivateSpaceTlsContextJksPost
type PrivateSpaceTlsContextJksPost struct {
	Name string `json:"name"`
	TlsConfig TlsConfigJks `json:"tlsConfig"`
	Ciphers Ciphers `json:"ciphers"`
}

// NewPrivateSpaceTlsContextJksPost instantiates a new PrivateSpaceTlsContextJksPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateSpaceTlsContextJksPost(name string, tlsConfig TlsConfigJks, ciphers Ciphers) *PrivateSpaceTlsContextJksPost {
	this := PrivateSpaceTlsContextJksPost{}
	this.Name = name
	this.TlsConfig = tlsConfig
	this.Ciphers = ciphers
	return &this
}

// NewPrivateSpaceTlsContextJksPostWithDefaults instantiates a new PrivateSpaceTlsContextJksPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateSpaceTlsContextJksPostWithDefaults() *PrivateSpaceTlsContextJksPost {
	this := PrivateSpaceTlsContextJksPost{}
	return &this
}

// GetName returns the Name field value
func (o *PrivateSpaceTlsContextJksPost) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceTlsContextJksPost) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PrivateSpaceTlsContextJksPost) SetName(v string) {
	o.Name = v
}

// GetTlsConfig returns the TlsConfig field value
func (o *PrivateSpaceTlsContextJksPost) GetTlsConfig() TlsConfigJks {
	if o == nil {
		var ret TlsConfigJks
		return ret
	}

	return o.TlsConfig
}

// GetTlsConfigOk returns a tuple with the TlsConfig field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceTlsContextJksPost) GetTlsConfigOk() (*TlsConfigJks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TlsConfig, true
}

// SetTlsConfig sets field value
func (o *PrivateSpaceTlsContextJksPost) SetTlsConfig(v TlsConfigJks) {
	o.TlsConfig = v
}

// GetCiphers returns the Ciphers field value
func (o *PrivateSpaceTlsContextJksPost) GetCiphers() Ciphers {
	if o == nil {
		var ret Ciphers
		return ret
	}

	return o.Ciphers
}

// GetCiphersOk returns a tuple with the Ciphers field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceTlsContextJksPost) GetCiphersOk() (*Ciphers, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ciphers, true
}

// SetCiphers sets field value
func (o *PrivateSpaceTlsContextJksPost) SetCiphers(v Ciphers) {
	o.Ciphers = v
}

func (o PrivateSpaceTlsContextJksPost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateSpaceTlsContextJksPost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["tlsConfig"] = o.TlsConfig
	toSerialize["ciphers"] = o.Ciphers
	return toSerialize, nil
}

type NullablePrivateSpaceTlsContextJksPost struct {
	value *PrivateSpaceTlsContextJksPost
	isSet bool
}

func (v NullablePrivateSpaceTlsContextJksPost) Get() *PrivateSpaceTlsContextJksPost {
	return v.value
}

func (v *NullablePrivateSpaceTlsContextJksPost) Set(val *PrivateSpaceTlsContextJksPost) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateSpaceTlsContextJksPost) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateSpaceTlsContextJksPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateSpaceTlsContextJksPost(val *PrivateSpaceTlsContextJksPost) *NullablePrivateSpaceTlsContextJksPost {
	return &NullablePrivateSpaceTlsContextJksPost{value: val, isSet: true}
}

func (v NullablePrivateSpaceTlsContextJksPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateSpaceTlsContextJksPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


