/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IngressConfigurationDeployment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IngressConfigurationDeployment{}

// IngressConfigurationDeployment struct for IngressConfigurationDeployment
type IngressConfigurationDeployment struct {
	Status string `json:"status"`
	LastSeenTimestamp float32 `json:"lastSeenTimestamp"`
}

// NewIngressConfigurationDeployment instantiates a new IngressConfigurationDeployment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIngressConfigurationDeployment(status string, lastSeenTimestamp float32) *IngressConfigurationDeployment {
	this := IngressConfigurationDeployment{}
	this.Status = status
	this.LastSeenTimestamp = lastSeenTimestamp
	return &this
}

// NewIngressConfigurationDeploymentWithDefaults instantiates a new IngressConfigurationDeployment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIngressConfigurationDeploymentWithDefaults() *IngressConfigurationDeployment {
	this := IngressConfigurationDeployment{}
	return &this
}

// GetStatus returns the Status field value
func (o *IngressConfigurationDeployment) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *IngressConfigurationDeployment) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *IngressConfigurationDeployment) SetStatus(v string) {
	o.Status = v
}

// GetLastSeenTimestamp returns the LastSeenTimestamp field value
func (o *IngressConfigurationDeployment) GetLastSeenTimestamp() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.LastSeenTimestamp
}

// GetLastSeenTimestampOk returns a tuple with the LastSeenTimestamp field value
// and a boolean to check if the value has been set.
func (o *IngressConfigurationDeployment) GetLastSeenTimestampOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastSeenTimestamp, true
}

// SetLastSeenTimestamp sets field value
func (o *IngressConfigurationDeployment) SetLastSeenTimestamp(v float32) {
	o.LastSeenTimestamp = v
}

func (o IngressConfigurationDeployment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IngressConfigurationDeployment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["lastSeenTimestamp"] = o.LastSeenTimestamp
	return toSerialize, nil
}

type NullableIngressConfigurationDeployment struct {
	value *IngressConfigurationDeployment
	isSet bool
}

func (v NullableIngressConfigurationDeployment) Get() *IngressConfigurationDeployment {
	return v.value
}

func (v *NullableIngressConfigurationDeployment) Set(val *IngressConfigurationDeployment) {
	v.value = val
	v.isSet = true
}

func (v NullableIngressConfigurationDeployment) IsSet() bool {
	return v.isSet
}

func (v *NullableIngressConfigurationDeployment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIngressConfigurationDeployment(val *IngressConfigurationDeployment) *NullableIngressConfigurationDeployment {
	return &NullableIngressConfigurationDeployment{value: val, isSet: true}
}

func (v NullableIngressConfigurationDeployment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIngressConfigurationDeployment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


