/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Network5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Network5{}

// Network5 Private space network configuration 
type Network5 struct {
	// The region of the Private Space. Required when create a Private Space network.
	Region *string `json:"region,omitempty"`
	// The existing VPC where the Private Space will be created. Required when create a Private Space in existing Anypoint VPC. 
	VpcId *string `json:"vpcId,omitempty"`
	// The CIDR block of the VPC where the Private Space will be created. Required when create a Private Space in a new VPC. Default is 10.0.0.0/16. 
	CidrBlock *string `json:"cidrBlock,omitempty"`
	InternalDns *InternalDns9 `json:"internalDns,omitempty"`
}

// NewNetwork5 instantiates a new Network5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetwork5() *Network5 {
	this := Network5{}
	var cidrBlock string = "10.0.0.0/16"
	this.CidrBlock = &cidrBlock
	return &this
}

// NewNetwork5WithDefaults instantiates a new Network5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetwork5WithDefaults() *Network5 {
	this := Network5{}
	var cidrBlock string = "10.0.0.0/16"
	this.CidrBlock = &cidrBlock
	return &this
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *Network5) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Network5) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *Network5) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *Network5) SetRegion(v string) {
	o.Region = &v
}

// GetVpcId returns the VpcId field value if set, zero value otherwise.
func (o *Network5) GetVpcId() string {
	if o == nil || IsNil(o.VpcId) {
		var ret string
		return ret
	}
	return *o.VpcId
}

// GetVpcIdOk returns a tuple with the VpcId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Network5) GetVpcIdOk() (*string, bool) {
	if o == nil || IsNil(o.VpcId) {
		return nil, false
	}
	return o.VpcId, true
}

// HasVpcId returns a boolean if a field has been set.
func (o *Network5) HasVpcId() bool {
	if o != nil && !IsNil(o.VpcId) {
		return true
	}

	return false
}

// SetVpcId gets a reference to the given string and assigns it to the VpcId field.
func (o *Network5) SetVpcId(v string) {
	o.VpcId = &v
}

// GetCidrBlock returns the CidrBlock field value if set, zero value otherwise.
func (o *Network5) GetCidrBlock() string {
	if o == nil || IsNil(o.CidrBlock) {
		var ret string
		return ret
	}
	return *o.CidrBlock
}

// GetCidrBlockOk returns a tuple with the CidrBlock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Network5) GetCidrBlockOk() (*string, bool) {
	if o == nil || IsNil(o.CidrBlock) {
		return nil, false
	}
	return o.CidrBlock, true
}

// HasCidrBlock returns a boolean if a field has been set.
func (o *Network5) HasCidrBlock() bool {
	if o != nil && !IsNil(o.CidrBlock) {
		return true
	}

	return false
}

// SetCidrBlock gets a reference to the given string and assigns it to the CidrBlock field.
func (o *Network5) SetCidrBlock(v string) {
	o.CidrBlock = &v
}

// GetInternalDns returns the InternalDns field value if set, zero value otherwise.
func (o *Network5) GetInternalDns() InternalDns9 {
	if o == nil || IsNil(o.InternalDns) {
		var ret InternalDns9
		return ret
	}
	return *o.InternalDns
}

// GetInternalDnsOk returns a tuple with the InternalDns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Network5) GetInternalDnsOk() (*InternalDns9, bool) {
	if o == nil || IsNil(o.InternalDns) {
		return nil, false
	}
	return o.InternalDns, true
}

// HasInternalDns returns a boolean if a field has been set.
func (o *Network5) HasInternalDns() bool {
	if o != nil && !IsNil(o.InternalDns) {
		return true
	}

	return false
}

// SetInternalDns gets a reference to the given InternalDns9 and assigns it to the InternalDns field.
func (o *Network5) SetInternalDns(v InternalDns9) {
	o.InternalDns = &v
}

func (o Network5) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Network5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.VpcId) {
		toSerialize["vpcId"] = o.VpcId
	}
	if !IsNil(o.CidrBlock) {
		toSerialize["cidrBlock"] = o.CidrBlock
	}
	if !IsNil(o.InternalDns) {
		toSerialize["internalDns"] = o.InternalDns
	}
	return toSerialize, nil
}

type NullableNetwork5 struct {
	value *Network5
	isSet bool
}

func (v NullableNetwork5) Get() *Network5 {
	return v.value
}

func (v *NullableNetwork5) Set(val *Network5) {
	v.value = val
	v.isSet = true
}

func (v NullableNetwork5) IsSet() bool {
	return v.isSet
}

func (v *NullableNetwork5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetwork5(val *Network5) *NullableNetwork5 {
	return &NullableNetwork5{value: val, isSet: true}
}

func (v NullableNetwork5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetwork5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


