/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Environments2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Environments2{}

// Environments2 Environment association for the Private Space 
type Environments2 struct {
	// The type of environments. Possible values are all, sandbox, production
	Type string `json:"type"`
	// The Ids of business groups.
	BusinessGroups []string `json:"businessGroups"`
}

// NewEnvironments2 instantiates a new Environments2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironments2(type_ string, businessGroups []string) *Environments2 {
	this := Environments2{}
	this.Type = type_
	this.BusinessGroups = businessGroups
	return &this
}

// NewEnvironments2WithDefaults instantiates a new Environments2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironments2WithDefaults() *Environments2 {
	this := Environments2{}
	return &this
}

// GetType returns the Type field value
func (o *Environments2) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Environments2) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Environments2) SetType(v string) {
	o.Type = v
}

// GetBusinessGroups returns the BusinessGroups field value
func (o *Environments2) GetBusinessGroups() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.BusinessGroups
}

// GetBusinessGroupsOk returns a tuple with the BusinessGroups field value
// and a boolean to check if the value has been set.
func (o *Environments2) GetBusinessGroupsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BusinessGroups, true
}

// SetBusinessGroups sets field value
func (o *Environments2) SetBusinessGroups(v []string) {
	o.BusinessGroups = v
}

func (o Environments2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Environments2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["businessGroups"] = o.BusinessGroups
	return toSerialize, nil
}

type NullableEnvironments2 struct {
	value *Environments2
	isSet bool
}

func (v NullableEnvironments2) Get() *Environments2 {
	return v.value
}

func (v *NullableEnvironments2) Set(val *Environments2) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironments2) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironments2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironments2(val *Environments2) *NullableEnvironments2 {
	return &NullableEnvironments2{value: val, isSet: true}
}

func (v NullableEnvironments2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironments2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


