/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Ciphers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Ciphers{}

// Ciphers struct for Ciphers
type Ciphers struct {
	Aes128GcmSha256 bool `json:"aes128GcmSha256"`
	Aes128Sha256 bool `json:"aes128Sha256"`
	Aes256GcmSha384 bool `json:"aes256GcmSha384"`
	Aes256Sha256 bool `json:"aes256Sha256"`
	DheRsaAes128Sha256 bool `json:"dheRsaAes128Sha256"`
	DheRsaAes256GcmSha384 bool `json:"dheRsaAes256GcmSha384"`
	DheRsaAes256Sha256 bool `json:"dheRsaAes256Sha256"`
	EcdheEcdsaAes128GcmSha256 bool `json:"ecdheEcdsaAes128GcmSha256"`
	EcdheEcdsaAes128Sha1 bool `json:"ecdheEcdsaAes128Sha1"`
	EcdheEcdsaAes256GcmSha384 bool `json:"ecdheEcdsaAes256GcmSha384"`
	EcdheEcdsaAes256Sha1 bool `json:"ecdheEcdsaAes256Sha1"`
	EcdheRsaAes128GcmSha256 bool `json:"ecdheRsaAes128GcmSha256"`
	EcdheRsaAes128Sha1 bool `json:"ecdheRsaAes128Sha1"`
	EcdheRsaAes256GcmSha384 bool `json:"ecdheRsaAes256GcmSha384"`
	EcdheRsaAes256Sha1 bool `json:"ecdheRsaAes256Sha1"`
	EcdheEcdsaChacha20Poly1305 bool `json:"ecdheEcdsaChacha20Poly1305"`
	EcdheRsaChacha20Poly1305 bool `json:"ecdheRsaChacha20Poly1305"`
	DheRsaChacha20Poly1305 bool `json:"dheRsaChacha20Poly1305"`
	TlsAes256GcmSha384 bool `json:"tlsAes256GcmSha384"`
	TlsChacha20Poly1305Sha256 bool `json:"tlsChacha20Poly1305Sha256"`
	TlsAes128GcmSha256 bool `json:"tlsAes128GcmSha256"`
}

// NewCiphers instantiates a new Ciphers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCiphers(aes128GcmSha256 bool, aes128Sha256 bool, aes256GcmSha384 bool, aes256Sha256 bool, dheRsaAes128Sha256 bool, dheRsaAes256GcmSha384 bool, dheRsaAes256Sha256 bool, ecdheEcdsaAes128GcmSha256 bool, ecdheEcdsaAes128Sha1 bool, ecdheEcdsaAes256GcmSha384 bool, ecdheEcdsaAes256Sha1 bool, ecdheRsaAes128GcmSha256 bool, ecdheRsaAes128Sha1 bool, ecdheRsaAes256GcmSha384 bool, ecdheRsaAes256Sha1 bool, ecdheEcdsaChacha20Poly1305 bool, ecdheRsaChacha20Poly1305 bool, dheRsaChacha20Poly1305 bool, tlsAes256GcmSha384 bool, tlsChacha20Poly1305Sha256 bool, tlsAes128GcmSha256 bool) *Ciphers {
	this := Ciphers{}
	this.Aes128GcmSha256 = aes128GcmSha256
	this.Aes128Sha256 = aes128Sha256
	this.Aes256GcmSha384 = aes256GcmSha384
	this.Aes256Sha256 = aes256Sha256
	this.DheRsaAes128Sha256 = dheRsaAes128Sha256
	this.DheRsaAes256GcmSha384 = dheRsaAes256GcmSha384
	this.DheRsaAes256Sha256 = dheRsaAes256Sha256
	this.EcdheEcdsaAes128GcmSha256 = ecdheEcdsaAes128GcmSha256
	this.EcdheEcdsaAes128Sha1 = ecdheEcdsaAes128Sha1
	this.EcdheEcdsaAes256GcmSha384 = ecdheEcdsaAes256GcmSha384
	this.EcdheEcdsaAes256Sha1 = ecdheEcdsaAes256Sha1
	this.EcdheRsaAes128GcmSha256 = ecdheRsaAes128GcmSha256
	this.EcdheRsaAes128Sha1 = ecdheRsaAes128Sha1
	this.EcdheRsaAes256GcmSha384 = ecdheRsaAes256GcmSha384
	this.EcdheRsaAes256Sha1 = ecdheRsaAes256Sha1
	this.EcdheEcdsaChacha20Poly1305 = ecdheEcdsaChacha20Poly1305
	this.EcdheRsaChacha20Poly1305 = ecdheRsaChacha20Poly1305
	this.DheRsaChacha20Poly1305 = dheRsaChacha20Poly1305
	this.TlsAes256GcmSha384 = tlsAes256GcmSha384
	this.TlsChacha20Poly1305Sha256 = tlsChacha20Poly1305Sha256
	this.TlsAes128GcmSha256 = tlsAes128GcmSha256
	return &this
}

// NewCiphersWithDefaults instantiates a new Ciphers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCiphersWithDefaults() *Ciphers {
	this := Ciphers{}
	var aes128GcmSha256 bool = false
	this.Aes128GcmSha256 = aes128GcmSha256
	var aes128Sha256 bool = false
	this.Aes128Sha256 = aes128Sha256
	var aes256GcmSha384 bool = false
	this.Aes256GcmSha384 = aes256GcmSha384
	var aes256Sha256 bool = false
	this.Aes256Sha256 = aes256Sha256
	var dheRsaAes128Sha256 bool = false
	this.DheRsaAes128Sha256 = dheRsaAes128Sha256
	var dheRsaAes256GcmSha384 bool = false
	this.DheRsaAes256GcmSha384 = dheRsaAes256GcmSha384
	var dheRsaAes256Sha256 bool = false
	this.DheRsaAes256Sha256 = dheRsaAes256Sha256
	var ecdheEcdsaAes128GcmSha256 bool = true
	this.EcdheEcdsaAes128GcmSha256 = ecdheEcdsaAes128GcmSha256
	var ecdheEcdsaAes128Sha1 bool = false
	this.EcdheEcdsaAes128Sha1 = ecdheEcdsaAes128Sha1
	var ecdheEcdsaAes256GcmSha384 bool = true
	this.EcdheEcdsaAes256GcmSha384 = ecdheEcdsaAes256GcmSha384
	var ecdheEcdsaAes256Sha1 bool = false
	this.EcdheEcdsaAes256Sha1 = ecdheEcdsaAes256Sha1
	var ecdheRsaAes128GcmSha256 bool = true
	this.EcdheRsaAes128GcmSha256 = ecdheRsaAes128GcmSha256
	var ecdheRsaAes128Sha1 bool = false
	this.EcdheRsaAes128Sha1 = ecdheRsaAes128Sha1
	var ecdheRsaAes256GcmSha384 bool = true
	this.EcdheRsaAes256GcmSha384 = ecdheRsaAes256GcmSha384
	var ecdheRsaAes256Sha1 bool = false
	this.EcdheRsaAes256Sha1 = ecdheRsaAes256Sha1
	var ecdheEcdsaChacha20Poly1305 bool = false
	this.EcdheEcdsaChacha20Poly1305 = ecdheEcdsaChacha20Poly1305
	var ecdheRsaChacha20Poly1305 bool = false
	this.EcdheRsaChacha20Poly1305 = ecdheRsaChacha20Poly1305
	var dheRsaChacha20Poly1305 bool = false
	this.DheRsaChacha20Poly1305 = dheRsaChacha20Poly1305
	var tlsAes256GcmSha384 bool = true
	this.TlsAes256GcmSha384 = tlsAes256GcmSha384
	var tlsChacha20Poly1305Sha256 bool = true
	this.TlsChacha20Poly1305Sha256 = tlsChacha20Poly1305Sha256
	var tlsAes128GcmSha256 bool = true
	this.TlsAes128GcmSha256 = tlsAes128GcmSha256
	return &this
}

// GetAes128GcmSha256 returns the Aes128GcmSha256 field value
func (o *Ciphers) GetAes128GcmSha256() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Aes128GcmSha256
}

// GetAes128GcmSha256Ok returns a tuple with the Aes128GcmSha256 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetAes128GcmSha256Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aes128GcmSha256, true
}

// SetAes128GcmSha256 sets field value
func (o *Ciphers) SetAes128GcmSha256(v bool) {
	o.Aes128GcmSha256 = v
}

// GetAes128Sha256 returns the Aes128Sha256 field value
func (o *Ciphers) GetAes128Sha256() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Aes128Sha256
}

// GetAes128Sha256Ok returns a tuple with the Aes128Sha256 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetAes128Sha256Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aes128Sha256, true
}

// SetAes128Sha256 sets field value
func (o *Ciphers) SetAes128Sha256(v bool) {
	o.Aes128Sha256 = v
}

// GetAes256GcmSha384 returns the Aes256GcmSha384 field value
func (o *Ciphers) GetAes256GcmSha384() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Aes256GcmSha384
}

// GetAes256GcmSha384Ok returns a tuple with the Aes256GcmSha384 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetAes256GcmSha384Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aes256GcmSha384, true
}

// SetAes256GcmSha384 sets field value
func (o *Ciphers) SetAes256GcmSha384(v bool) {
	o.Aes256GcmSha384 = v
}

// GetAes256Sha256 returns the Aes256Sha256 field value
func (o *Ciphers) GetAes256Sha256() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Aes256Sha256
}

// GetAes256Sha256Ok returns a tuple with the Aes256Sha256 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetAes256Sha256Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aes256Sha256, true
}

// SetAes256Sha256 sets field value
func (o *Ciphers) SetAes256Sha256(v bool) {
	o.Aes256Sha256 = v
}

// GetDheRsaAes128Sha256 returns the DheRsaAes128Sha256 field value
func (o *Ciphers) GetDheRsaAes128Sha256() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DheRsaAes128Sha256
}

// GetDheRsaAes128Sha256Ok returns a tuple with the DheRsaAes128Sha256 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetDheRsaAes128Sha256Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DheRsaAes128Sha256, true
}

// SetDheRsaAes128Sha256 sets field value
func (o *Ciphers) SetDheRsaAes128Sha256(v bool) {
	o.DheRsaAes128Sha256 = v
}

// GetDheRsaAes256GcmSha384 returns the DheRsaAes256GcmSha384 field value
func (o *Ciphers) GetDheRsaAes256GcmSha384() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DheRsaAes256GcmSha384
}

// GetDheRsaAes256GcmSha384Ok returns a tuple with the DheRsaAes256GcmSha384 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetDheRsaAes256GcmSha384Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DheRsaAes256GcmSha384, true
}

// SetDheRsaAes256GcmSha384 sets field value
func (o *Ciphers) SetDheRsaAes256GcmSha384(v bool) {
	o.DheRsaAes256GcmSha384 = v
}

// GetDheRsaAes256Sha256 returns the DheRsaAes256Sha256 field value
func (o *Ciphers) GetDheRsaAes256Sha256() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DheRsaAes256Sha256
}

// GetDheRsaAes256Sha256Ok returns a tuple with the DheRsaAes256Sha256 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetDheRsaAes256Sha256Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DheRsaAes256Sha256, true
}

// SetDheRsaAes256Sha256 sets field value
func (o *Ciphers) SetDheRsaAes256Sha256(v bool) {
	o.DheRsaAes256Sha256 = v
}

// GetEcdheEcdsaAes128GcmSha256 returns the EcdheEcdsaAes128GcmSha256 field value
func (o *Ciphers) GetEcdheEcdsaAes128GcmSha256() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EcdheEcdsaAes128GcmSha256
}

// GetEcdheEcdsaAes128GcmSha256Ok returns a tuple with the EcdheEcdsaAes128GcmSha256 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetEcdheEcdsaAes128GcmSha256Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EcdheEcdsaAes128GcmSha256, true
}

// SetEcdheEcdsaAes128GcmSha256 sets field value
func (o *Ciphers) SetEcdheEcdsaAes128GcmSha256(v bool) {
	o.EcdheEcdsaAes128GcmSha256 = v
}

// GetEcdheEcdsaAes128Sha1 returns the EcdheEcdsaAes128Sha1 field value
func (o *Ciphers) GetEcdheEcdsaAes128Sha1() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EcdheEcdsaAes128Sha1
}

// GetEcdheEcdsaAes128Sha1Ok returns a tuple with the EcdheEcdsaAes128Sha1 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetEcdheEcdsaAes128Sha1Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EcdheEcdsaAes128Sha1, true
}

// SetEcdheEcdsaAes128Sha1 sets field value
func (o *Ciphers) SetEcdheEcdsaAes128Sha1(v bool) {
	o.EcdheEcdsaAes128Sha1 = v
}

// GetEcdheEcdsaAes256GcmSha384 returns the EcdheEcdsaAes256GcmSha384 field value
func (o *Ciphers) GetEcdheEcdsaAes256GcmSha384() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EcdheEcdsaAes256GcmSha384
}

// GetEcdheEcdsaAes256GcmSha384Ok returns a tuple with the EcdheEcdsaAes256GcmSha384 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetEcdheEcdsaAes256GcmSha384Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EcdheEcdsaAes256GcmSha384, true
}

// SetEcdheEcdsaAes256GcmSha384 sets field value
func (o *Ciphers) SetEcdheEcdsaAes256GcmSha384(v bool) {
	o.EcdheEcdsaAes256GcmSha384 = v
}

// GetEcdheEcdsaAes256Sha1 returns the EcdheEcdsaAes256Sha1 field value
func (o *Ciphers) GetEcdheEcdsaAes256Sha1() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EcdheEcdsaAes256Sha1
}

// GetEcdheEcdsaAes256Sha1Ok returns a tuple with the EcdheEcdsaAes256Sha1 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetEcdheEcdsaAes256Sha1Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EcdheEcdsaAes256Sha1, true
}

// SetEcdheEcdsaAes256Sha1 sets field value
func (o *Ciphers) SetEcdheEcdsaAes256Sha1(v bool) {
	o.EcdheEcdsaAes256Sha1 = v
}

// GetEcdheRsaAes128GcmSha256 returns the EcdheRsaAes128GcmSha256 field value
func (o *Ciphers) GetEcdheRsaAes128GcmSha256() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EcdheRsaAes128GcmSha256
}

// GetEcdheRsaAes128GcmSha256Ok returns a tuple with the EcdheRsaAes128GcmSha256 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetEcdheRsaAes128GcmSha256Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EcdheRsaAes128GcmSha256, true
}

// SetEcdheRsaAes128GcmSha256 sets field value
func (o *Ciphers) SetEcdheRsaAes128GcmSha256(v bool) {
	o.EcdheRsaAes128GcmSha256 = v
}

// GetEcdheRsaAes128Sha1 returns the EcdheRsaAes128Sha1 field value
func (o *Ciphers) GetEcdheRsaAes128Sha1() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EcdheRsaAes128Sha1
}

// GetEcdheRsaAes128Sha1Ok returns a tuple with the EcdheRsaAes128Sha1 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetEcdheRsaAes128Sha1Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EcdheRsaAes128Sha1, true
}

// SetEcdheRsaAes128Sha1 sets field value
func (o *Ciphers) SetEcdheRsaAes128Sha1(v bool) {
	o.EcdheRsaAes128Sha1 = v
}

// GetEcdheRsaAes256GcmSha384 returns the EcdheRsaAes256GcmSha384 field value
func (o *Ciphers) GetEcdheRsaAes256GcmSha384() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EcdheRsaAes256GcmSha384
}

// GetEcdheRsaAes256GcmSha384Ok returns a tuple with the EcdheRsaAes256GcmSha384 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetEcdheRsaAes256GcmSha384Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EcdheRsaAes256GcmSha384, true
}

// SetEcdheRsaAes256GcmSha384 sets field value
func (o *Ciphers) SetEcdheRsaAes256GcmSha384(v bool) {
	o.EcdheRsaAes256GcmSha384 = v
}

// GetEcdheRsaAes256Sha1 returns the EcdheRsaAes256Sha1 field value
func (o *Ciphers) GetEcdheRsaAes256Sha1() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EcdheRsaAes256Sha1
}

// GetEcdheRsaAes256Sha1Ok returns a tuple with the EcdheRsaAes256Sha1 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetEcdheRsaAes256Sha1Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EcdheRsaAes256Sha1, true
}

// SetEcdheRsaAes256Sha1 sets field value
func (o *Ciphers) SetEcdheRsaAes256Sha1(v bool) {
	o.EcdheRsaAes256Sha1 = v
}

// GetEcdheEcdsaChacha20Poly1305 returns the EcdheEcdsaChacha20Poly1305 field value
func (o *Ciphers) GetEcdheEcdsaChacha20Poly1305() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EcdheEcdsaChacha20Poly1305
}

// GetEcdheEcdsaChacha20Poly1305Ok returns a tuple with the EcdheEcdsaChacha20Poly1305 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetEcdheEcdsaChacha20Poly1305Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EcdheEcdsaChacha20Poly1305, true
}

// SetEcdheEcdsaChacha20Poly1305 sets field value
func (o *Ciphers) SetEcdheEcdsaChacha20Poly1305(v bool) {
	o.EcdheEcdsaChacha20Poly1305 = v
}

// GetEcdheRsaChacha20Poly1305 returns the EcdheRsaChacha20Poly1305 field value
func (o *Ciphers) GetEcdheRsaChacha20Poly1305() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EcdheRsaChacha20Poly1305
}

// GetEcdheRsaChacha20Poly1305Ok returns a tuple with the EcdheRsaChacha20Poly1305 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetEcdheRsaChacha20Poly1305Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EcdheRsaChacha20Poly1305, true
}

// SetEcdheRsaChacha20Poly1305 sets field value
func (o *Ciphers) SetEcdheRsaChacha20Poly1305(v bool) {
	o.EcdheRsaChacha20Poly1305 = v
}

// GetDheRsaChacha20Poly1305 returns the DheRsaChacha20Poly1305 field value
func (o *Ciphers) GetDheRsaChacha20Poly1305() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DheRsaChacha20Poly1305
}

// GetDheRsaChacha20Poly1305Ok returns a tuple with the DheRsaChacha20Poly1305 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetDheRsaChacha20Poly1305Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DheRsaChacha20Poly1305, true
}

// SetDheRsaChacha20Poly1305 sets field value
func (o *Ciphers) SetDheRsaChacha20Poly1305(v bool) {
	o.DheRsaChacha20Poly1305 = v
}

// GetTlsAes256GcmSha384 returns the TlsAes256GcmSha384 field value
func (o *Ciphers) GetTlsAes256GcmSha384() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TlsAes256GcmSha384
}

// GetTlsAes256GcmSha384Ok returns a tuple with the TlsAes256GcmSha384 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetTlsAes256GcmSha384Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TlsAes256GcmSha384, true
}

// SetTlsAes256GcmSha384 sets field value
func (o *Ciphers) SetTlsAes256GcmSha384(v bool) {
	o.TlsAes256GcmSha384 = v
}

// GetTlsChacha20Poly1305Sha256 returns the TlsChacha20Poly1305Sha256 field value
func (o *Ciphers) GetTlsChacha20Poly1305Sha256() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TlsChacha20Poly1305Sha256
}

// GetTlsChacha20Poly1305Sha256Ok returns a tuple with the TlsChacha20Poly1305Sha256 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetTlsChacha20Poly1305Sha256Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TlsChacha20Poly1305Sha256, true
}

// SetTlsChacha20Poly1305Sha256 sets field value
func (o *Ciphers) SetTlsChacha20Poly1305Sha256(v bool) {
	o.TlsChacha20Poly1305Sha256 = v
}

// GetTlsAes128GcmSha256 returns the TlsAes128GcmSha256 field value
func (o *Ciphers) GetTlsAes128GcmSha256() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TlsAes128GcmSha256
}

// GetTlsAes128GcmSha256Ok returns a tuple with the TlsAes128GcmSha256 field value
// and a boolean to check if the value has been set.
func (o *Ciphers) GetTlsAes128GcmSha256Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TlsAes128GcmSha256, true
}

// SetTlsAes128GcmSha256 sets field value
func (o *Ciphers) SetTlsAes128GcmSha256(v bool) {
	o.TlsAes128GcmSha256 = v
}

func (o Ciphers) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Ciphers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["aes128GcmSha256"] = o.Aes128GcmSha256
	toSerialize["aes128Sha256"] = o.Aes128Sha256
	toSerialize["aes256GcmSha384"] = o.Aes256GcmSha384
	toSerialize["aes256Sha256"] = o.Aes256Sha256
	toSerialize["dheRsaAes128Sha256"] = o.DheRsaAes128Sha256
	toSerialize["dheRsaAes256GcmSha384"] = o.DheRsaAes256GcmSha384
	toSerialize["dheRsaAes256Sha256"] = o.DheRsaAes256Sha256
	toSerialize["ecdheEcdsaAes128GcmSha256"] = o.EcdheEcdsaAes128GcmSha256
	toSerialize["ecdheEcdsaAes128Sha1"] = o.EcdheEcdsaAes128Sha1
	toSerialize["ecdheEcdsaAes256GcmSha384"] = o.EcdheEcdsaAes256GcmSha384
	toSerialize["ecdheEcdsaAes256Sha1"] = o.EcdheEcdsaAes256Sha1
	toSerialize["ecdheRsaAes128GcmSha256"] = o.EcdheRsaAes128GcmSha256
	toSerialize["ecdheRsaAes128Sha1"] = o.EcdheRsaAes128Sha1
	toSerialize["ecdheRsaAes256GcmSha384"] = o.EcdheRsaAes256GcmSha384
	toSerialize["ecdheRsaAes256Sha1"] = o.EcdheRsaAes256Sha1
	toSerialize["ecdheEcdsaChacha20Poly1305"] = o.EcdheEcdsaChacha20Poly1305
	toSerialize["ecdheRsaChacha20Poly1305"] = o.EcdheRsaChacha20Poly1305
	toSerialize["dheRsaChacha20Poly1305"] = o.DheRsaChacha20Poly1305
	toSerialize["tlsAes256GcmSha384"] = o.TlsAes256GcmSha384
	toSerialize["tlsChacha20Poly1305Sha256"] = o.TlsChacha20Poly1305Sha256
	toSerialize["tlsAes128GcmSha256"] = o.TlsAes128GcmSha256
	return toSerialize, nil
}

type NullableCiphers struct {
	value *Ciphers
	isSet bool
}

func (v NullableCiphers) Get() *Ciphers {
	return v.value
}

func (v *NullableCiphers) Set(val *Ciphers) {
	v.value = val
	v.isSet = true
}

func (v NullableCiphers) IsSet() bool {
	return v.isSet
}

func (v *NullableCiphers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCiphers(val *Ciphers) *NullableCiphers {
	return &NullableCiphers{value: val, isSet: true}
}

func (v NullableCiphers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCiphers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


