/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PrivateSpaceIngressConfigurationLogsFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateSpaceIngressConfigurationLogsFilter{}

// PrivateSpaceIngressConfigurationLogsFilter struct for PrivateSpaceIngressConfigurationLogsFilter
type PrivateSpaceIngressConfigurationLogsFilter struct {
	Ip *string `json:"ip,omitempty"`
	Level *string `json:"level,omitempty"`
}

// NewPrivateSpaceIngressConfigurationLogsFilter instantiates a new PrivateSpaceIngressConfigurationLogsFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateSpaceIngressConfigurationLogsFilter() *PrivateSpaceIngressConfigurationLogsFilter {
	this := PrivateSpaceIngressConfigurationLogsFilter{}
	return &this
}

// NewPrivateSpaceIngressConfigurationLogsFilterWithDefaults instantiates a new PrivateSpaceIngressConfigurationLogsFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateSpaceIngressConfigurationLogsFilterWithDefaults() *PrivateSpaceIngressConfigurationLogsFilter {
	this := PrivateSpaceIngressConfigurationLogsFilter{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *PrivateSpaceIngressConfigurationLogsFilter) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateSpaceIngressConfigurationLogsFilter) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *PrivateSpaceIngressConfigurationLogsFilter) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *PrivateSpaceIngressConfigurationLogsFilter) SetIp(v string) {
	o.Ip = &v
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *PrivateSpaceIngressConfigurationLogsFilter) GetLevel() string {
	if o == nil || IsNil(o.Level) {
		var ret string
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateSpaceIngressConfigurationLogsFilter) GetLevelOk() (*string, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *PrivateSpaceIngressConfigurationLogsFilter) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given string and assigns it to the Level field.
func (o *PrivateSpaceIngressConfigurationLogsFilter) SetLevel(v string) {
	o.Level = &v
}

func (o PrivateSpaceIngressConfigurationLogsFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateSpaceIngressConfigurationLogsFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	return toSerialize, nil
}

type NullablePrivateSpaceIngressConfigurationLogsFilter struct {
	value *PrivateSpaceIngressConfigurationLogsFilter
	isSet bool
}

func (v NullablePrivateSpaceIngressConfigurationLogsFilter) Get() *PrivateSpaceIngressConfigurationLogsFilter {
	return v.value
}

func (v *NullablePrivateSpaceIngressConfigurationLogsFilter) Set(val *PrivateSpaceIngressConfigurationLogsFilter) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateSpaceIngressConfigurationLogsFilter) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateSpaceIngressConfigurationLogsFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateSpaceIngressConfigurationLogsFilter(val *PrivateSpaceIngressConfigurationLogsFilter) *NullablePrivateSpaceIngressConfigurationLogsFilter {
	return &NullablePrivateSpaceIngressConfigurationLogsFilter{value: val, isSet: true}
}

func (v NullablePrivateSpaceIngressConfigurationLogsFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateSpaceIngressConfigurationLogsFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


