/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PrivateSpaceTransitGatewayPost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateSpaceTransitGatewayPost{}

// PrivateSpaceTransitGatewayPost struct for PrivateSpaceTransitGatewayPost
type PrivateSpaceTransitGatewayPost struct {
	Name string `json:"name"`
	ResourceShareId string `json:"resourceShareId"`
	ResourceShareAccount string `json:"resourceShareAccount"`
	Routes []string `json:"routes"`
}

// NewPrivateSpaceTransitGatewayPost instantiates a new PrivateSpaceTransitGatewayPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateSpaceTransitGatewayPost(name string, resourceShareId string, resourceShareAccount string, routes []string) *PrivateSpaceTransitGatewayPost {
	this := PrivateSpaceTransitGatewayPost{}
	this.Name = name
	this.ResourceShareId = resourceShareId
	this.ResourceShareAccount = resourceShareAccount
	this.Routes = routes
	return &this
}

// NewPrivateSpaceTransitGatewayPostWithDefaults instantiates a new PrivateSpaceTransitGatewayPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateSpaceTransitGatewayPostWithDefaults() *PrivateSpaceTransitGatewayPost {
	this := PrivateSpaceTransitGatewayPost{}
	return &this
}

// GetName returns the Name field value
func (o *PrivateSpaceTransitGatewayPost) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceTransitGatewayPost) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PrivateSpaceTransitGatewayPost) SetName(v string) {
	o.Name = v
}

// GetResourceShareId returns the ResourceShareId field value
func (o *PrivateSpaceTransitGatewayPost) GetResourceShareId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceShareId
}

// GetResourceShareIdOk returns a tuple with the ResourceShareId field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceTransitGatewayPost) GetResourceShareIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceShareId, true
}

// SetResourceShareId sets field value
func (o *PrivateSpaceTransitGatewayPost) SetResourceShareId(v string) {
	o.ResourceShareId = v
}

// GetResourceShareAccount returns the ResourceShareAccount field value
func (o *PrivateSpaceTransitGatewayPost) GetResourceShareAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceShareAccount
}

// GetResourceShareAccountOk returns a tuple with the ResourceShareAccount field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceTransitGatewayPost) GetResourceShareAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceShareAccount, true
}

// SetResourceShareAccount sets field value
func (o *PrivateSpaceTransitGatewayPost) SetResourceShareAccount(v string) {
	o.ResourceShareAccount = v
}

// GetRoutes returns the Routes field value
func (o *PrivateSpaceTransitGatewayPost) GetRoutes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Routes
}

// GetRoutesOk returns a tuple with the Routes field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceTransitGatewayPost) GetRoutesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Routes, true
}

// SetRoutes sets field value
func (o *PrivateSpaceTransitGatewayPost) SetRoutes(v []string) {
	o.Routes = v
}

func (o PrivateSpaceTransitGatewayPost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateSpaceTransitGatewayPost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["resourceShareId"] = o.ResourceShareId
	toSerialize["resourceShareAccount"] = o.ResourceShareAccount
	toSerialize["routes"] = o.Routes
	return toSerialize, nil
}

type NullablePrivateSpaceTransitGatewayPost struct {
	value *PrivateSpaceTransitGatewayPost
	isSet bool
}

func (v NullablePrivateSpaceTransitGatewayPost) Get() *PrivateSpaceTransitGatewayPost {
	return v.value
}

func (v *NullablePrivateSpaceTransitGatewayPost) Set(val *PrivateSpaceTransitGatewayPost) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateSpaceTransitGatewayPost) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateSpaceTransitGatewayPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateSpaceTransitGatewayPost(val *PrivateSpaceTransitGatewayPost) *NullablePrivateSpaceTransitGatewayPost {
	return &NullablePrivateSpaceTransitGatewayPost{value: val, isSet: true}
}

func (v NullablePrivateSpaceTransitGatewayPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateSpaceTransitGatewayPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


