/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Subject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Subject{}

// Subject Details about the entity to which the certificate is issued.
type Subject struct {
	CommonName string `json:"commonName"`
	CountryName string `json:"countryName"`
	LocalityName string `json:"localityName"`
	OrganizationName string `json:"organizationName"`
	OrganizationUnit string `json:"organizationUnit"`
	State string `json:"state"`
}

// NewSubject instantiates a new Subject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubject(commonName string, countryName string, localityName string, organizationName string, organizationUnit string, state string) *Subject {
	this := Subject{}
	this.CommonName = commonName
	this.CountryName = countryName
	this.LocalityName = localityName
	this.OrganizationName = organizationName
	this.OrganizationUnit = organizationUnit
	this.State = state
	return &this
}

// NewSubjectWithDefaults instantiates a new Subject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubjectWithDefaults() *Subject {
	this := Subject{}
	return &this
}

// GetCommonName returns the CommonName field value
func (o *Subject) GetCommonName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommonName
}

// GetCommonNameOk returns a tuple with the CommonName field value
// and a boolean to check if the value has been set.
func (o *Subject) GetCommonNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommonName, true
}

// SetCommonName sets field value
func (o *Subject) SetCommonName(v string) {
	o.CommonName = v
}

// GetCountryName returns the CountryName field value
func (o *Subject) GetCountryName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryName
}

// GetCountryNameOk returns a tuple with the CountryName field value
// and a boolean to check if the value has been set.
func (o *Subject) GetCountryNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryName, true
}

// SetCountryName sets field value
func (o *Subject) SetCountryName(v string) {
	o.CountryName = v
}

// GetLocalityName returns the LocalityName field value
func (o *Subject) GetLocalityName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LocalityName
}

// GetLocalityNameOk returns a tuple with the LocalityName field value
// and a boolean to check if the value has been set.
func (o *Subject) GetLocalityNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocalityName, true
}

// SetLocalityName sets field value
func (o *Subject) SetLocalityName(v string) {
	o.LocalityName = v
}

// GetOrganizationName returns the OrganizationName field value
func (o *Subject) GetOrganizationName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationName
}

// GetOrganizationNameOk returns a tuple with the OrganizationName field value
// and a boolean to check if the value has been set.
func (o *Subject) GetOrganizationNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationName, true
}

// SetOrganizationName sets field value
func (o *Subject) SetOrganizationName(v string) {
	o.OrganizationName = v
}

// GetOrganizationUnit returns the OrganizationUnit field value
func (o *Subject) GetOrganizationUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationUnit
}

// GetOrganizationUnitOk returns a tuple with the OrganizationUnit field value
// and a boolean to check if the value has been set.
func (o *Subject) GetOrganizationUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationUnit, true
}

// SetOrganizationUnit sets field value
func (o *Subject) SetOrganizationUnit(v string) {
	o.OrganizationUnit = v
}

// GetState returns the State field value
func (o *Subject) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *Subject) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *Subject) SetState(v string) {
	o.State = v
}

func (o Subject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Subject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["commonName"] = o.CommonName
	toSerialize["countryName"] = o.CountryName
	toSerialize["localityName"] = o.LocalityName
	toSerialize["organizationName"] = o.OrganizationName
	toSerialize["organizationUnit"] = o.OrganizationUnit
	toSerialize["state"] = o.State
	return toSerialize, nil
}

type NullableSubject struct {
	value *Subject
	isSet bool
}

func (v NullableSubject) Get() *Subject {
	return v.value
}

func (v *NullableSubject) Set(val *Subject) {
	v.value = val
	v.isSet = true
}

func (v NullableSubject) IsSet() bool {
	return v.isSet
}

func (v *NullableSubject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubject(val *Subject) *NullableSubject {
	return &NullableSubject{value: val, isSet: true}
}

func (v NullableSubject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


