/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PrivateSpaceTransitGatewayPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateSpaceTransitGatewayPatch{}

// PrivateSpaceTransitGatewayPatch struct for PrivateSpaceTransitGatewayPatch
type PrivateSpaceTransitGatewayPatch struct {
	Name string `json:"name"`
}

// NewPrivateSpaceTransitGatewayPatch instantiates a new PrivateSpaceTransitGatewayPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateSpaceTransitGatewayPatch(name string) *PrivateSpaceTransitGatewayPatch {
	this := PrivateSpaceTransitGatewayPatch{}
	this.Name = name
	return &this
}

// NewPrivateSpaceTransitGatewayPatchWithDefaults instantiates a new PrivateSpaceTransitGatewayPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateSpaceTransitGatewayPatchWithDefaults() *PrivateSpaceTransitGatewayPatch {
	this := PrivateSpaceTransitGatewayPatch{}
	return &this
}

// GetName returns the Name field value
func (o *PrivateSpaceTransitGatewayPatch) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceTransitGatewayPatch) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PrivateSpaceTransitGatewayPatch) SetName(v string) {
	o.Name = v
}

func (o PrivateSpaceTransitGatewayPatch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateSpaceTransitGatewayPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullablePrivateSpaceTransitGatewayPatch struct {
	value *PrivateSpaceTransitGatewayPatch
	isSet bool
}

func (v NullablePrivateSpaceTransitGatewayPatch) Get() *PrivateSpaceTransitGatewayPatch {
	return v.value
}

func (v *NullablePrivateSpaceTransitGatewayPatch) Set(val *PrivateSpaceTransitGatewayPatch) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateSpaceTransitGatewayPatch) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateSpaceTransitGatewayPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateSpaceTransitGatewayPatch(val *PrivateSpaceTransitGatewayPatch) *NullablePrivateSpaceTransitGatewayPatch {
	return &NullablePrivateSpaceTransitGatewayPatch{value: val, isSet: true}
}

func (v NullablePrivateSpaceTransitGatewayPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateSpaceTransitGatewayPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


