/*
CH2 Management API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PrivateSpaceTransitGateway type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateSpaceTransitGateway{}

// PrivateSpaceTransitGateway struct for PrivateSpaceTransitGateway
type PrivateSpaceTransitGateway struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Spec TgwSpec `json:"spec"`
	Status TgwStatus `json:"status"`
}

// NewPrivateSpaceTransitGateway instantiates a new PrivateSpaceTransitGateway object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateSpaceTransitGateway(id string, name string, spec TgwSpec, status TgwStatus) *PrivateSpaceTransitGateway {
	this := PrivateSpaceTransitGateway{}
	this.Id = id
	this.Name = name
	this.Spec = spec
	this.Status = status
	return &this
}

// NewPrivateSpaceTransitGatewayWithDefaults instantiates a new PrivateSpaceTransitGateway object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateSpaceTransitGatewayWithDefaults() *PrivateSpaceTransitGateway {
	this := PrivateSpaceTransitGateway{}
	return &this
}

// GetId returns the Id field value
func (o *PrivateSpaceTransitGateway) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceTransitGateway) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PrivateSpaceTransitGateway) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *PrivateSpaceTransitGateway) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceTransitGateway) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PrivateSpaceTransitGateway) SetName(v string) {
	o.Name = v
}

// GetSpec returns the Spec field value
func (o *PrivateSpaceTransitGateway) GetSpec() TgwSpec {
	if o == nil {
		var ret TgwSpec
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceTransitGateway) GetSpecOk() (*TgwSpec, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *PrivateSpaceTransitGateway) SetSpec(v TgwSpec) {
	o.Spec = v
}

// GetStatus returns the Status field value
func (o *PrivateSpaceTransitGateway) GetStatus() TgwStatus {
	if o == nil {
		var ret TgwStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PrivateSpaceTransitGateway) GetStatusOk() (*TgwStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PrivateSpaceTransitGateway) SetStatus(v TgwStatus) {
	o.Status = v
}

func (o PrivateSpaceTransitGateway) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateSpaceTransitGateway) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["spec"] = o.Spec
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

type NullablePrivateSpaceTransitGateway struct {
	value *PrivateSpaceTransitGateway
	isSet bool
}

func (v NullablePrivateSpaceTransitGateway) Get() *PrivateSpaceTransitGateway {
	return v.value
}

func (v *NullablePrivateSpaceTransitGateway) Set(val *PrivateSpaceTransitGateway) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateSpaceTransitGateway) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateSpaceTransitGateway) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateSpaceTransitGateway(val *PrivateSpaceTransitGateway) *NullablePrivateSpaceTransitGateway {
	return &NullablePrivateSpaceTransitGateway{value: val, isSet: true}
}

func (v NullablePrivateSpaceTransitGateway) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateSpaceTransitGateway) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


